### ISSUE TITLE
The issues of Benchmark

### ISSUE THREAD

**Issue by zhaoxiang0715** [yixiao1/CILv2_multiview#1]
I got this error when executing the command "run. /scripts/run_evaluation/CILv2/nocrash_newweathertown_Town02.sh"
./scripts/run_evaluation/CILv2/nocrash_newweathertown_Town02.sh
Traceback (most recent call last):
  File "/home/zx/CILv2_multiview/run_CARLA_driving//driving/evaluator.py", line 36, in <module>
    from driving.scenarios.scenario_manager import ScenarioManager
  File "/home/zx/CILv2_multiview/run_CARLA_driving/driving/scenarios/scenario_manager.py", line 26, in <module>
    from driving.autoagents.agent_wrapper import AgentWrapper, AgentError
  File "/home/zx/CILv2_multiview/run_CARLA_driving/driving/autoagents/agent_wrapper.py", line 19, in <module>
    from driving.autoagents.autonomous_agent import Track
  File "/home/zx/CILv2_multiview/run_CARLA_driving/driving/autoagents/autonomous_agent.py", line 17, in <module>
    from driving.utils.route_manipulation import downsample_route
  File "/home/zx/CILv2_multiview/run_CARLA_driving/driving/utils/route_manipulation.py", line 17, in <module>
    from agents.navigation.global_route_planner_dao import GlobalRoutePlannerDAO
ModuleNotFoundError: No module named 'agents.navigation.global_route_planner_dao'
 PYTHON_RETURN=1!!! Start Over!!!
I looked through carla's documentation and couldn't find a solution. Could you help with that, please? 
Thank you very much

**Comment by yixiao1** [comment]
> I got this error when executing the command "run. /scripts/run_evaluation/CILv2/nocrash_newweathertown_Town02.sh" ./scripts/run_evaluation/CILv2/nocrash_newweathertown_Town02.sh Traceback (most recent call last): File "/home/zx/CILv2_multiview/run_CARLA_driving//driving/evaluator.py", line 36, in from driving.scenarios.scenario_manager import ScenarioManager File "/home/zx/CILv2_multiview/run_CARLA_driving/driving/scenarios/scenario_manager.py", line 26, in from driving.autoagents.agent_wrapper import AgentWrapper, AgentError File "/home/zx/CILv2_multiview/run_CARLA_driving/driving/autoagents/agent_wrapper.py", line 19, in from driving.autoagents.autonomous_agent import Track File "/home/zx/CILv2_multiview/run_CARLA_driving/driving/autoagents/autonomous_agent.py", line 17, in from driving.utils.route_manipulation import downsample_route File "/home/zx/CILv2_multiview/run_CARLA_driving/driving/utils/route_manipulation.py", line 17, in from agents.navigation.global_route_planner_dao import GlobalRoutePlannerDAO ModuleNotFoundError: No module named 'agents.navigation.global_route_planner_dao' PYTHON_RETURN=1!!! Start Over!!! I looked through carla's documentation and couldn't find a solution. Could you help with that, please? Thank you very much

Hi Zhaoxiang,

Thanks for the question. The issue was caused by me merging some CARLA PythonAPI files locally.
I've updated the code, please check and see if the problem is solved. Let me know if you have more issues. Thanks.

Bests,
Yi

**Comment by zhaoxiang0715** [comment]
> > I got this error when executing the command "run. /scripts/run_evaluation/CILv2/nocrash_newweathertown_Town02.sh" ./scripts/run_evaluation/CILv2/nocrash_newweathertown_Town02.sh Traceback (most recent call last): File "/home/zx/CILv2_multiview/run_CARLA_driving//driving/evaluator.py", line 36, in from driving.scenarios.scenario_manager import ScenarioManager File "/home/zx/CILv2_multiview/run_CARLA_driving/driving/scenarios/scenario_manager.py", line 26, in from driving.autoagents.agent_wrapper import AgentWrapper, AgentError File "/home/zx/CILv2_multiview/run_CARLA_driving/driving/autoagents/agent_wrapper.py", line 19, in from driving.autoagents.autonomous_agent import Track File "/home/zx/CILv2_multiview/run_CARLA_driving/driving/autoagents/autonomous_agent.py", line 17, in from driving.utils.route_manipulation import downsample_route File "/home/zx/CILv2_multiview/run_CARLA_driving/driving/utils/route_manipulation.py", line 17, in from agents.navigation.global_route_planner_dao import GlobalRoutePlannerDAO ModuleNotFoundError: No module named 'agents.navigation.global_route_planner_dao' PYTHON_RETURN=1!!! Start Over!!! I looked through carla's documentation and couldn't find a solution. Could you help with that, please? Thank you very much我在执行命令“run./scripts/run_evaluation/CILv2/nocrash_newweathertown_Town02.sh“ ./scripts/run_evaluation/CILv2/nocrash_newweathertown_Town02.sh 回溯（最近一次调用最后一次）： 文件”/home/zx/CILv2_multiview/run_CARLA_driving//driving/evaluator.py“，第 36 行，从 driving.scenarios.scenario_manager 导入 ScenarioManager 文件 ”/home/zx/CILv2_multiview/run_CARLA_driving/driving/scenarios/scenario_manager.py“，第 26 行，从 driving.autoagents.agent_wrapper 导入 AgentWrapper， AgentError 文件 “/home/zx/CILv2_multiview/run_CARLA_driving/driving/autoagents/agent_wrapper.py”，第 19 行，从 driving.autoagents.autonomous_agent 导入 跟踪文件“/home/zx/CILv2_multiview/run_CARLA_driving/driving/autoagents/autonomous_agent.py”，第 17 行，从 driving.utils.route_manipulation导入 downsample_route 文件 “/home/zx/CILv2_multiview/run_CARLA_driving/driving/utils/route_manipulation.py”，第 17 行， in from agents.navigation.global_route_planner_dao import GlobalRoutePlannerDAO ModuleNotFoundError： No module named 'agents.navigation.global_route_planner_dao' PYTHON_RETURN=1!!重新开始!!我浏览了 carla 的文档，找不到解决方案。你能帮忙吗？谢谢
> 
> Hi Zhaoxiang, 嗨，兆祥，
> 
> Thanks for the question. The issue was caused by me merging some CARLA PythonAPI files locally.谢谢你的问题。该问题是由于我在本地合并了一些 CARLA PythonAPI 文件引起的。 I've updated the code, please check and see if the problem is solved. Let me know if you have more issues. Thanks.我已经更新了代码，请检查一下问题是否解决。如果您有更多问题，请告诉我。谢谢。
> 
> Bests, 最好的， Yi 吃

Dear Yixiao,
Thank you for helping me solve the above problems, but in the process of running, I found new problems, as follows:
========= Preparing SoftRainSunset_route00000 (repetition 0) =========
> Setting up the agent
/home/zx/CILv2_multiview/configs/_global.py:81: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml_file = yaml.load(f)
CILv2_multiview_attention_45.pth loaded from  /home/zx/CILv2_multiview/_results/Ours/Town1_2/checkpoints
> Loading the world
  port: 36329
Set seed for pedestrians: 0
Set seed for traffic manager: 0
Set seed for numpy: 0
Set seed for random state: 0

The scenario could not be loaded:
> __init__() missing 1 required positional argument: 'memory'

Traceback (most recent call last):
  File "/home/zx/CILv2_multiview/run_CARLA_driving//driving/evaluator.py", line 327, in _load_and_run_scenario
    scenario = RouteScenario(world=self.world, config=config, debug_mode=args.debug)
  File "/home/zx/CILv2_multiview/run_CARLA_driving/driving/scenarios/route_scenario.py", line 193, in __init__
    super(RouteScenario, self).__init__(name=config.name,
  File "/home/zx/CILv2_multiview/scenario_runner/srunner/scenarios/basic_scenario.py", line 61, in __init__
    behavior = self._create_behavior()
  File "/home/zx/CILv2_multiview/run_CARLA_driving/driving/scenarios/route_scenario.py", line 548, in _create_behavior
    sequence = py_trees.composites.Sequence("RouteScenario")
TypeError: __init__() missing 1 required positional argument: 'memory'
Could you help with that, please?
Thank you very much！

**Comment by yixiao1** [comment]
Hi @zhaoxiang0715,

> File "/home/zx/CILv2_multiview/run_CARLA_driving/driving/scenarios/route_scenario.py", line 548, in _create_behavior
sequence = py_trees.composites.Sequence("RouteScenario")
> TypeError: init() missing 1 required positional argument: 'memory'

Please try to reinstall the py-trees with the version of 0.8.3.

Bests,
Yi

**Comment by Wangxuecheng666** [comment]
> > I got this error when executing the command "run. /scripts/run_evaluation/CILv2/nocrash_newweathertown_Town02.sh" ./scripts/run_evaluation/CILv2/nocrash_newweathertown_Town02.sh Traceback (most recent call last): File "/home/zx/CILv2_multiview/run_CARLA_driving//driving/evaluator.py", line 36, in from driving.scenarios.scenario_manager import ScenarioManager File "/home/zx/CILv2_multiview/run_CARLA_driving/driving/scenarios/scenario_manager.py", line 26, in from driving.autoagents.agent_wrapper import AgentWrapper, AgentError File "/home/zx/CILv2_multiview/run_CARLA_driving/driving/autoagents/agent_wrapper.py", line 19, in from driving.autoagents.autonomous_agent import Track File "/home/zx/CILv2_multiview/run_CARLA_driving/driving/autoagents/autonomous_agent.py", line 17, in from driving.utils.route_manipulation import downsample_route File "/home/zx/CILv2_multiview/run_CARLA_driving/driving/utils/route_manipulation.py", line 17, in from agents.navigation.global_route_planner_dao import GlobalRoutePlannerDAO ModuleNotFoundError: No module named 'agents.navigation.global_route_planner_dao' PYTHON_RETURN=1!!! Start Over!!! I looked through carla's documentation and couldn't find a solution. Could you help with that, please? Thank you very much
> 
> Hi Zhaoxiang,
> 
> Thanks for the question. The issue was caused by me merging some CARLA PythonAPI files locally. I've updated the code, please check and see if the problem is solved. Let me know if you have more issues. Thanks.
> 
> Bests, Yi

I'm using what should be the updated code but I'm still experiencing this problem, what can I do to fix it please, thanks!



    from srunner.scenariomanager.scenarioatomics.atomic_behaviors import Idle, ScenarioTriggerer
  File "/mnt/wxc/wxc_work_pr/CILv2_multiview/scenario_runner/srunner/scenariomanager/scenarioatomics/atomic_behaviors.py", line 34, in <module>
    from agents.navigation.global_route_planner_dao import GlobalRoutePlannerDAO
ModuleNotFoundError: No module named 'agents.navigation.global_route_planner_dao'

**Comment by yixiao1** [comment]
> I'm using what should be the updated code but I'm still experiencing this problem, what can I do to fix it please, thanks!
> 
> ```
> from srunner.scenariomanager.scenarioatomics.atomic_behaviors import Idle, ScenarioTriggerer
> ```
> 
> File "/mnt/wxc/wxc_work_pr/CILv2_multiview/scenario_runner/srunner/scenariomanager/scenarioatomics/atomic_behaviors.py", line 34, in from agents.navigation.global_route_planner_dao import GlobalRoutePlannerDAO ModuleNotFoundError: No module named 'agents.navigation.global_route_planner_dao'

Hi,
Thanks for reporting the issue. 
I've updated some files in ../scenario_runner/srunner/scenariomanager/scenarioatomics/.., please update your code with git pull. Please let me know if the issue is not resolved.
Thanks.

Best wishes,
Yi
