### ISSUE TITLE
Is there a script for data collection from Roach RL expert?

### ISSUE THREAD

**Issue by donghaiwang** [yixiao1/CILv2_multiview#3]
Carla keeps crashing when I run Roach RL expert. Can you share the process of training and evaluating Roach RL expert? Thank you.

**Comment by donghaiwang** [comment]
Where are the evaluation results saved by the `save_dict` function in the `CILv2_multiview\run_CARLA_driving\driving\utils\checkpoint_tools.py` script?
And how to get metrics in your paper using script, including SR, S.SR, T.L, Avg.RC, Avg.DS, C.V, C.L, T.L, O.L,  R.Dev. 
Think you. @yixiao1 

╒═══════════════════════╤═════════╤═════════╕
│ Criterion             │ Result  │ Value   │
├───────────────────────┼─────────┼─────────┤
│ RouteCompletionTest   │ SUCCESS │ 100 %   │
├───────────────────────┼─────────┼─────────┤
│ OutsideRouteLanesTest │ FAILURE │ 0.64 %  │
├───────────────────────┼─────────┼─────────┤
│ CollisionTest         │ SUCCESS │ 0 times │
├───────────────────────┼─────────┼─────────┤
│ RunningRedLightTest   │ FAILURE │ 3 times │
├───────────────────────┼─────────┼─────────┤
│ InRouteTest           │ SUCCESS │         │
├───────────────────────┼─────────┼─────────┤
│ AgentBlockedTest      │ SUCCESS │         │
├───────────────────────┼─────────┼─────────┤
│ Timeout               │ SUCCESS │         │
╘═══════════════════════╧═════════╧═════════╛

> Registering the route statistics
> Registering the global statistics
Finished all episode. Goodbye!
KQKCTGIGT5P5468MXTXP63Z0P59KSNT5BZHAB92LYQXD0S3ENSEO3T90LX8G70TB
 PYTHON_RETURN=0!!! Start Over!!!
Bash script done.

**Comment by yixiao1** [comment]
> Carla keeps crashing when I run Roach RL expert. Can you share the process of training and evaluating Roach RL expert? Thank you.

Hi, sorry for the late reply. 
We don’t train a new Roach RL expert agent but directly run the model provided in [this GitHub](https://github.com/zhejz/carla-roach). We used this agent as our expert agent to collect data, so training and evaluating it is not the focus for our paper.
Please refer to their page and follow the instructions to run Roach RL agent.
